# 列表如何转为ndarray

In [3]:
#列表转ndarray
import numpy as np

list1 = [1, 2, 3, 4]
print(list1)
print(type(list1))



[1, 2, 3, 4]
<class 'list'>


In [4]:
oneArray = np.array(list1)
# array()函数可以将列表转换为ndarray
print(type(oneArray))  #类型是ndarray
print(oneArray)

<class 'numpy.ndarray'>
[1 2 3 4]


# ndarray与Python原生list运算效率对比

In [5]:
import random
import time
import numpy as np

#随机1亿个list数据
a = []
for i in range(100000000):
    a.append(random.random())
print('随机完毕')

随机完毕


In [6]:
b = np.array(a)  # 转换为ndarray
print('转换完毕')

转换完毕


In [7]:
#ndarray的计算效率优于python的list
t1 = time.time()
sum1 = sum(a)
t2 = time.time()

t4 = time.time()
sum3 = np.sum(b)
t5 = time.time()
print(t2 - t1, t5 - t4)

0.29909348487854004 0.07918167114257812


In [8]:
t1 = np.array([1, 2, 3])
print(t1)
print(type(t1))

[1 2 3]
<class 'numpy.ndarray'>


In [9]:
# range()函数返回一个range对象，不能直接转换为ndarray
print(type(range(10)))  # range返回的是一个range对象，不能直接转换为ndarray
t2 = np.array(range(10))
print(t2)
print(type(t2))

<class 'range'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [10]:
# rang和arange函数的区别
# arange函数的数可以是整数也可以是浮点数
# range只能是整数，且返回range,不能直接返回ndarray
t3 = np.arange(0, 10, 2)  # 等价于range(0,10,2),返回ndarray
print(t3)
print(type(t3))

[0 2 4 6 8]
<class 'numpy.ndarray'>


In [11]:
#二维列表转ndarray
import numpy as np

list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
print(type(twoArray))
print(twoArray)
print(list2)  #列表的输出是有逗号的，ndarray的输出是没有逗号的

<class 'numpy.ndarray'>
[[1 2]
 [3 4]
 [5 6]]
[[1, 2], [3, 4], [5, 6]]


In [12]:
twoArray.tolist()  # ndarray转换为列表

[[1, 2], [3, 4], [5, 6]]

# 4.3 常用属性

In [13]:
#看ndarray的各种属性
list2 = [[1, 2], [3, 4], [5, 6]]

twoArray = np.array(list2)
# 获取数组的维度( 注意： 与函数的参数很像) 
print(twoArray.ndim)

# 形状（行，列） (0 axis,1 axis)
print(twoArray.shape)

# 有多少个元素
print(twoArray.size)
# 数据类型
print(twoArray.dtype)  #默认int32,4个字节，数据范围 -21亿到21亿

2
(3, 2)
6
int32


# 4.4 调整数组的形状

In [5]:
four = np.array([[1, 2, 3], [4, 5, 6]])

print(four)
# 修改的是原有的
four1 = four
print(id(four))
print(id(four1))

[[1 2 3]
 [4 5 6]]
1823187208592
1823187208592


In [15]:
four.shape = (3, 2)  # 改变形状
print(id(four))
print(id(four1))
print(four)

1922834210736
1922834210736
[[1 2]
 [3 4]
 [5 6]]


In [17]:
print('-' * 50)
# 返回一个新的数组，reshape后id和之前的不一样
four2 = four.reshape(2, 3)
print(four)
print(id(four))
print(id(four2))
four2

--------------------------------------------------
[[1 2]
 [3 4]
 [5 6]]
1922834210736
1925835961904


array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# 将多维变成一维数组
# 讲解reshape()函数
# reshape()函数可以改变数组的形状，但是不能改变元素的个数
# reshape()函数返回一个新的数组，原数组不变
# reshape()函数可以指定新的形状，也可以不指定，不指定则根据元素个数自动计算
# reshape()函数可以指定元素的顺序，‘C’为行主序，‘F’为列主序
five = four.reshape((6,), order='C')
# 默认情况下‘C’以行为主的顺序展开，‘F’（Fortran风格）意味着以列的顺序展开
six = four.flatten()  # 展开成一维数组
print(five)
print('-' * 50)
print(six)

# print(five.reshape(3,2))

[1 2 3 4 5 6]
--------------------------------------------------
[1 2 3 4 5 6]


In [20]:
seven = five.reshape(3, 2)  # 改变形状
seven

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
print('-' * 50)
# 拓展：数组的形状
t = np.arange(24)  #和列表的range函数一样，生成一个数组
print(t)
print(f'shape{t.shape}')
print(t.ndim)
# 转换成二维
t1 = t.reshape((4, 6))
print(t1)
print(t1.shape)

--------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
shape(24,)
1
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)


In [25]:
# 转成三维
#最前面的是零轴，轴越小，越靠外，最小的轴是最外层
# 0轴，1轴，2轴
t2 = t.reshape((2, 3, 4))
print(t2)
print(t2.shape)
print(t2.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
3


In [26]:
t3 = t.reshape((2, 3, 2, 2))
print(t3)
print(t3.shape)
print(t3.ndim)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]]


 [[[12 13]
   [14 15]]

  [[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]]
(2, 3, 2, 2)
4


4.5 数组转换为列表

In [27]:
#将数组转换为列表 tolist
a = np.array([9, 12, 88, 14, 25])
print(type(a))
list_a = a.tolist()
print(list_a)
print(type(list_a))


<class 'numpy.ndarray'>
[9, 12, 88, 14, 25]
<class 'list'>


# 5 NumPy的数据类型

In [41]:
import random

# 为什么转换数据要dtpye？
# 1. 节省内存
# 2. 节省时间
# 3. 保证数据的准确性
f = np.array([1, 2, 3, 4, 127], dtype=np.int8)  # 返回数组中每个元素的字节单位长度,dtype设置数据类型
print(f.itemsize)  # 1 np.int16(一个字节)
# 获取数据类型
print(f.dtype)

1
int8


In [42]:
f[4] = f[4] + 1  #溢出

In [43]:
f[4]

-128

In [31]:
# 调整数据类型
# astype()函数可以将数组的数据类型转换为另一种类型
# astype()函数返回一个新的数组，原数组不变
f1 = f.astype(np.int64)
print(f1.dtype)
print(f1.itemsize)  #显示字节数
print('-' * 50)

int64
8
--------------------------------------------------


In [44]:
random.random()  # 随机生成0-1之间的小数

0.7286964288500806

In [45]:
# 拓展随机生成小数
# 使用python语法，保留两位
print(round(random.random(), 2))
# round(..., 2)负责精加工（将其标准化为两位小数）
# np.float16 半精度
arr = np.array([random.random() for i in range(10)])
print(arr)
print(arr.itemsize)
print(arr.dtype)
# 取小数点后两位
print(np.round(arr, 2))

0.84
[0.11206566 0.91793226 0.84856337 0.98588934 0.95315264 0.14406265
 0.35482501 0.86209711 0.91629262 0.57545547]
8
float64
[0.11 0.92 0.85 0.99 0.95 0.14 0.35 0.86 0.92 0.58]


# 数组和数的计算

In [46]:
# [1,2,3]+2 不能直接加整数，需要使用np.array()

TypeError: can only concatenate list (not "int") to list

In [47]:
# 由于numpy的广播机机制在运算过程中，加减乘除的值被广播到所有的元素上面
t1 = np.arange(24).reshape((6, 4))
print(t1)
print("-" * 20)
t2 = t1.tolist()
print(t1 + 2)
# print(t2+2) 不能对列表进行直接加整数操作
print("-" * 20)
print(t1 * 2)
print("-" * 20)
print(t1 / 2)

#无论多少维的ndarray都可以直接和一个常数进行运算

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
--------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
--------------------
[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]
 [32 34 36 38]
 [40 42 44 46]]
--------------------
[[ 0.   0.5  1.   1.5]
 [ 2.   2.5  3.   3.5]
 [ 4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5]
 [ 8.   8.5  9.   9.5]
 [10.  10.5 11.  11.5]]


ndarray与ndarray的运算

In [49]:
#形状相同,才可以进行加减乘除
t1 = np.arange(24).reshape((6, 4))
t2 = np.arange(100, 124).reshape((6, 4))
print(t1)
print(t2)
print('-' * 50)
print(t1 + t2)
print('-' * 50)
print(t1 * t2)  #是否是矩阵乘法？不是


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]
 [120 121 122 123]]
--------------------------------------------------
[[100 102 104 106]
 [108 110 112 114]
 [116 118 120 122]
 [124 126 128 130]
 [132 134 136 138]
 [140 142 144 146]]
--------------------------------------------------
[[   0  101  204  309]
 [ 416  525  636  749]
 [ 864  981 1100 1221]
 [1344 1469 1596 1725]
 [1856 1989 2124 2261]
 [2400 2541 2684 2829]]


In [50]:
#shape不同，不能进行运算
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((3, 6))
print(t1)
print(t2)
print(t1 - t2)

ValueError: cannot reshape array of size 6 into shape (3,6)

In [51]:
#一维数组和二维数组进行运算时，一维的元素个数和列数相等
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(6).reshape((1, 6))
print(t2.shape)
print(t1)
print(t2)
t1 - t2


(1, 6)
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[0 1 2 3 4 5]]


array([[ 0,  0,  0,  0,  0,  0],
       [ 6,  6,  6,  6,  6,  6],
       [12, 12, 12, 12, 12, 12],
       [18, 18, 18, 18, 18, 18]])

In [52]:
(t1 - t2).shape

(4, 6)

In [53]:
t1 = np.arange(24).reshape((4, 6))
t2 = np.arange(4).reshape((4, 1))
print(t2)
print(t1)
t1 - t2


[[0]
 [1]
 [2]
 [3]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


array([[ 0,  1,  2,  3,  4,  5],
       [ 5,  6,  7,  8,  9, 10],
       [10, 11, 12, 13, 14, 15],
       [15, 16, 17, 18, 19, 20]])

In [2]:
#随机3维数组
import numpy as np
a = np.arange(24).reshape((2, 3, 4))
b = np.arange(12).reshape((1, 3, 4))
print(a)
print(b)
print('-' * 50)
a - b

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
--------------------------------------------------


array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]]])

结论：ndim要相同，可以某一个轴的size不同，但是其中一个ndarray必须对应的轴的size为1

# 练习轴

In [55]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print("-" * 20)
print(np.sum(a, axis=0))  # [5 7 9]，按哪个轴求和，哪个轴没了
print("-" * 20)
print(np.sum(a, axis=1))  # [ 6 15]
print("-" * 20)
print(np.sum(a))
print("-" * 20)


[[1 2 3]
 [4 5 6]]
--------------------
[5 7 9]
--------------------
[ 6 15]
--------------------
21
--------------------


In [8]:
# 难点
a = np.arange(24).reshape((2, 3, 4))
print(a)
b = np.sum(a, axis=0)
print("-" * 20)
print(b)
print(b.shape)
c = np.sum(a, axis=1)
print("-" * 20)
print(c)
print(c.shape)
d = np.sum(a, axis=2)
print("-" * 20)
print(d)
print(d.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------------
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
(3, 4)
--------------------
[[12 15 18 21]
 [48 51 54 57]]
(2, 4)
--------------------
[[ 6 22 38]
 [54 70 86]]
(2, 3)


# 索引和切片

In [57]:
import numpy as np

a = np.arange(10)
# 冒号分隔切片参数 start:stop:step 来进行切片操作print(a[2:7:2])# 从索引 2 开始到索引 7 停止，间隔为 2

# 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[0], a)

# 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

print(a[2:8:2])  #切片是左闭右开


0 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]
[2 4 6]


In [58]:
import numpy as np

t1 = np.arange(24).reshape(4, 6)
print(t1)
print('*' * 20)
print(t1[1])  # 取一行(一行代表是一条数据，索引也是从0开始的) print(t1[1,:]) # 取一行
print('*' * 20)
print(t1[1:])  # 取连续的多行
print('*' * 20)
print(t1[1:3, :])  # 取连续的多行
print('*' * 20)
print(t1[[0, 2, 3]])   # 取不连续的多行 

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[ 6  7  8  9 10 11]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
********************
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
********************
[[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [4]:
#看列表
t2 = np.arange(24).reshape(4, 6).tolist()
print(t2)
t2[[0, 2, 3]]

[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23]]


TypeError: list indices must be integers or slices, not list

In [60]:
print(t1[:, 1])  # 取一列
print('*' * 20)
print(t1[:, 1:])  # 连续的多列
print('*' * 20)
print(t1[:, [0, 2, 3]])  # 取不连续的多列
print('*' * 20)
print(t1[2, 3])  # # 取某一个值,三行四列  py是t1[2][3]
print('*' * 20)
print(t1[[0, 1, 1], [0, 1, 3]])  # 取多个不连续的值，[[行，行。。。],[列，列。。。]]

t1[1:3, 1:4]  #取1-3行，1-4列

[ 1  7 13 19]
********************
[[ 1  2  3  4  5]
 [ 7  8  9 10 11]
 [13 14 15 16 17]
 [19 20 21 22 23]]
********************
[[ 0  2  3]
 [ 6  8  9]
 [12 14 15]
 [18 20 21]]
********************
15
********************
[0 7 9]


array([[ 7,  8,  9],
       [13, 14, 15]])

# 修改值

In [16]:
import numpy as np

t = np.arange(24).reshape(4, 6)
print(t)
print(id(t))
print('-' * 50)
# # 修改某一行的值
# t[1,:]=0
#
# # 修改某一列的值
# t[:,1]=0
#
# # 修改连续多行
# t[1:3,:]=0
#
# # 修改连续多列
# t[:,1:4]=0
#
# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:3,2:5]=0
#
# # 修改多个不相邻的点
# t[[0,1],[1,3]]=0

# 可以根据条件修改，比如讲小于10的值改掉
# t[t<10]=0

# 使用逻辑判断
# np.logical_and	& # np.logical_or	|
# np.logical_not		~
# t[(t>2)&(t<6)]=0	# 逻辑与，and
# t[(t<2)|(t>6)]=0	# 逻辑或，or
# t[~(t>6)]=0	# 逻辑非
# print(t)
# 讲解clip()函数
# clip()函数可以将数组中的元素限制在一个范围之内，超出范围的元素将被替换为边界值。
# 语法：arr.clip(a_min, a_max, out=None)
# 参数：a_min：最小值，a_max：最大值，out：输出数组，默认为None。
# 返回：返回一个新的数组，包含原数组中每个元素的限制在a_min和a_max之间的版本。
# 比10小的数字变为10，比18大的数字变为18
t = t.clip(10, 18)
print(id(t))
'''
思考两次t的地址为什么不同？
t = np.arange(24).reshape(4, 6)是创建一个ndarray对象，然后标签t指向这个对象，
t = t.clip(10, 18)是对当前标签的对象，进行加工然后在赋予一个新的对象，还用标签t
对于生成新的对象操作方法有，clip()函数，reshape()函数，sum()函数等等，
这些操作都不会改变原来的对象，而是生成一个新的对象，所以t的地址不同。
'''
t


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
1823187220688
--------------------------------------------------
1823187202768


array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 18, 18, 18, 18, 18]])

In [17]:
t = np.arange(24).reshape(4, 6)
t < 10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [71]:
#python的三目运算
a = 10
b = 15
c = a if a > b else b
c

15

In [72]:
# # 拓 展
# # 三目运算（ np.where(condition, x, y)满足条件(condition)，输出x，不满足输出y。)）
score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
result = np.where(score < 80, True, False)  #类似于if else
print(result)


[[80 88]
 [82 81]
 [75 81]]
[[False False]
 [False False]
 [ True False]]


In [73]:
# 采用bool索引 + 广播机制赋值
score[result] = 100
score

array([[ 80,  88],
       [ 82,  81],
       [100,  81]])

# 数据的添加，删除与去重

In [76]:
# 1. numpy.append 函数在数组的末尾添加值。 追加操作会分配整个数组，并把原来的数组复制到新数组中。
# append不会修改原始数组，而是返回一个新的数组。
# 此外，输入数组的维度必须匹配否则将生成ValueError。
'''
参 数 说 明 ：                                                                                arr： 输 入 数 组                                                                             values：要向arr添加的值，需要和arr形状相同（除了要添加的轴）                                        axis：默认为 None。当axis无定义时，是横向加成，返回总是为一维数组！当axis有定义的时候，分别为0和1的时候。当
axis有定义的时候，分别为0和1的时候（列数要相同）。当axis为1时，数组是加在右边（行数要相同）。
'''
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

print('第一个数组：')
print(a)
print('\n')

print(' 向 数 组 添 加 元 素 ：')
print(np.append(a, [7, 8, 9]))  #ndarray会被展平
print('\n')
print(a)
print('-' * 50)


第一个数组：
[[1 2 3]
 [4 5 6]]


 向 数 组 添 加 元 素 ：
[1 2 3 4 5 6 7 8 9]


[[1 2 3]
 [4 5 6]]
--------------------------------------------------


In [77]:
b = np.array([[7, 8, 9]])
print(b.ndim)
print(b)
print('-' * 50)

2
[[7 8 9]]
--------------------------------------------------


In [78]:
print('沿轴 0 添加元素：')  #往哪个轴添加，那个轴size就变大
print(np.append(a, [[7, 8, 9]], axis=0))
print('\n')
print(a)
print('沿轴 1 添加元素：')
print(np.append(a, [[5, 5, 5], [7, 8, 9]], axis=1))
print(a)
print('-' * 50)


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1 2 3]
 [4 5 6]]
沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]
[[1 2 3]
 [4 5 6]]
--------------------------------------------------


In [79]:
# # 2. numpy.insert
# # 函数在给定索引之前，沿给定轴在输入数组中插入值。# 如果值的类型转换为要插入，则它与输入数组不同。
# # 插入没有原地的，函数会返回一个新数组。 此外，如果未提供轴，则输入数组会被展开。
# numpy.insert(arr, obj, values, axis=None)
# 参数：arr：输入数组，如果不是一维数组则会展平
# obj：可以被切片，整数或者整数数组，表明要插入的位置，从0开始
# values：要插入的值，可以是单个值，也可以是一维数组

a = np.array([[1, 2], [3, 4], [5, 6]])

print('第一个数组：')
print(a)
print('\n')

print('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print(np.insert(a, 1, [11, 22]))
print('-' * 50)
print(np.insert(a, 1, [11, 12], axis=0))  #那个轴插入，哪个轴size变大
# print('传递了 Axis 参数。 会广播值数组来配输入数组。')

print('沿轴  0 广播：')
print(np.insert(a, 1, 11, axis=0))
print('\n')

print('沿轴  1 广播：')
print(np.insert(a, 1, [1, 2, 5], axis=1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1 11 22  2  3  4  5  6]
--------------------------------------------------
[[ 1  2]
 [11 12]
 [ 3  4]
 [ 5  6]]
沿轴  0 广播：
[[ 1  2]
 [11 11]
 [ 3  4]
 [ 5  6]]


沿轴  1 广播：
[[1 1 2]
 [3 2 4]
 [5 5 6]]


In [80]:
#numpy.delete 函数返回从输入数组中删除指定子数组的新数组。 与 insert() 函数的情况一样，
# 如果未提供轴参数， 则输入数组将展开。
'''
参 数 说 明 ： arr： 输 入 数 组
obj：可以被切片，整数或者整数数组，表明要从输入数组删除的子数组axis：
沿着它删除给定子数组的轴，如果未提供，则输入数组会被展开
'''
import numpy as np

a = np.arange(12).reshape(3, 4)

print('第一个数组：')
print(a)
print('\n')

print('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print(np.delete(a, 5))
print('\n')
print(a)
print('删除第一行：')
print(np.delete(a, 1, axis=0))
print('\n')

print('删除第一列：')
print(np.delete(a, 1, axis=1))

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
删除第一行：
[[ 0  1  2  3]
 [ 8  9 10 11]]


删除第一列：
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [18]:
# numpy.unique 函数用于去除数组中的重复元素。
# 查找并返回输入数组中的唯一元素（去重），并按升序排序
'''
numpy.unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None)
arr：输入数组，如果不是一维数组则会展平
return_index：如果为true，返回新列表元素在旧列表中的位置（下标），并以列表形式储，多返回一个数组
return_inverse：如果为true，返回旧列表元素在新列表中的位置（下标），并以列表形式储
return_counts：如果为true，返回去重数组中的元素在原数组中的出现次数
'''
import numpy as np

a = np.array([5, 2, 6, 2, 7, 5, 6, 9, 8, 2])

print('第一个数组：')
print(a)
print('\n')

#去除重复元素，输出的是有序序列
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')

# print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print(u)
print (indices)
print ('\n')

print ('我们可以看到每个和原数组下标对应的数值：')
print ('去重数组的下标：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print (indices)
print ('\n')

print('返回去重元素的重复数量：')
u, indices = np.unique(a, return_counts=True)
print(u)
print(indices)
u

第一个数组：
[5 2 6 2 7 5 6 9 8 2]


第一个数组的去重值：
[2 5 6 7 8 9]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


array([2, 5, 6, 7, 8, 9])

# numpy的数学计算

In [85]:
import numpy as np

score = np.array([[80, 88], [82, 81], [75, 81]])
print(score)
# 1. 获取所有数据最大值
result = np.max(score)
print(result)
# 2. 获取某一个轴上的数据最大值，对应的轴就消失
result = np.max(score, axis=1)
print(result)
# 3. 获取最小值
result = np.min(score)
print(result)
# 4. 获取某一个轴上的数据最小值
result = np.min(score, axis=0)
print(result)
# 5. 数据的比较
result = np.maximum([-2, -1, 0, 1, 2], 0)  # 第一个参数中的每一个数与第二个参数比较返回大的
print(result)
result = np.minimum([-2, -1, 0, 1, 2], 0)  # 第一个参数中的每一个数与第二个参数比较返回小的
print(result)
result = np.maximum([-2, -1, 4, 1, 2], [1, 2, 3, 4, 5])
print(result)
# 接受的两个参数，也可以大小一致;第二个参数只是一个单独的值时，其实是用到了维度的广播机制；


'''通用函数：
numpy.sqrt(array)	平方根函数
numpy.exp(array)	e^array[i]的数组
numpy.abs/fabs(array)	计算绝对值
numpy.square(array)	计算各元素的平方 等于array	2
numpy.log/log10/log2(array)	计算各元素的各种对数
numpy.sign(array)	计算各元素正负号
numpy.isnan(array)	计算各元素是否为NaN
numpy.isinf(array)	计算各元素是否为NaN
numpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数
numpy.modf(array)	将array中值得整数和小数分离，作两个数组返回
numpy.ceil(array)	向上取整,也就是取比这个数大的整数
numpy.floor(array)	向下取整,也就是取比这个数小的整数
numpy.rint(array)	四舍五入
numpy.trunc(array)	向0取整
numpy.cos(array)	正弦值
numpy.sin(array)	余弦值
numpy.tan(array)	正切值

numpy.add(array1,array2)	元素级加法
numpy.subtract(array1,array2)	元素级减法
numpy.multiply(array1,array2)	元素级乘法
numpy.divide(array1,array2)	元素级除法 array1./array2
numpy.power(array1,array2)	元素级指数 array1.^array2
numpy.maximum/minimum(array1,aray2) 元素级最大值
numpy.fmax/fmin(array1,array2)	元素级最大值，忽略NaN
numpy.mod(array1,array2)	元素级求模
numpy.copysign(array1,array2)	将第二个数组中值得符号复制给第一个数组中值
numpy.greater/greater_equal/less/less_equal/equal/not_equal (array1,array2)
元素级比较运算，产生布尔数组
numpy.logical_end/logical_or/logic_xor(array1,array2)元素级的真值逻辑运算
'''



[[80 88]
 [82 81]
 [75 81]]
88
[88 82 81]
75
[75 81]
[0 0 0 1 2]
[-2 -1  0  0  0]
[1 2 4 4 5]


'通用函数：\nnumpy.sqrt(array)\t平方根函数\nnumpy.exp(array)\te^array[i]的数组\nnumpy.abs/fabs(array)\t计算绝对值\nnumpy.square(array)\t计算各元素的平方 等于array\t2\nnumpy.log/log10/log2(array)\t计算各元素的各种对数\nnumpy.sign(array)\t计算各元素正负号\nnumpy.isnan(array)\t计算各元素是否为NaN\nnumpy.isinf(array)\t计算各元素是否为NaN\nnumpy.cos/cosh/sin/sinh/tan/tanh(array) 三角函数\nnumpy.modf(array)\t将array中值得整数和小数分离，作两个数组返回\nnumpy.ceil(array)\t向上取整,也就是取比这个数大的整数\nnumpy.floor(array)\t向下取整,也就是取比这个数小的整数\nnumpy.rint(array)\t四舍五入\nnumpy.trunc(array)\t向0取整\nnumpy.cos(array)\t正弦值\nnumpy.sin(array)\t余弦值\nnumpy.tan(array)\t正切值\n\nnumpy.add(array1,array2)\t元素级加法\nnumpy.subtract(array1,array2)\t元素级减法\nnumpy.multiply(array1,array2)\t元素级乘法\nnumpy.divide(array1,array2)\t元素级除法 array1./array2\nnumpy.power(array1,array2)\t元素级指数 array1.^array2\nnumpy.maximum/minimum(array1,aray2) 元素级最大值\nnumpy.fmax/fmin(array1,array2)\t元素级最大值，忽略NaN\nnumpy.mod(array1,array2)\t元素级求模\nnumpy.copysign(array1,array2)\t将第二个数组中值得符号复制给第一个数组中值\nnumpy.greater/greater_equal/less/less_equal/equa

In [86]:
# 6. 求平均值
result = np.mean(score)  # 获取所有数据的平均值
print(result)
result = np.mean(score, axis=0)  # 获取某一行或者某一列的平均值
print(result)
# 7. 求前缀和
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.cumsum(axis=0))
'''
[1, 2, 3]------>	|1	|2	|3	|
[4, 5, 6]------>	|5=1+4 |7=2+5 |9=3+6|
'''
print(arr.cumsum(axis=1))
'''
[1, 2, 3]------>	|1	|2+1	|3+2+1	|
[4, 5, 6]------>	|4	|4+5	|4+5+6	|
'''



# 拓展：方差var, 协方差cov, 计算平均值 average, 计算中位数 median

81.16666666666667
[79.         83.33333333]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]


'\n[1, 2, 3]------>\t|1\t|2+1\t|3+2+1\t|\n[4, 5, 6]------>\t|4\t|4+5\t|4+5+6\t|\n'

In [48]:
# 8. argmin求最小值索引
result = np.argmin(score, axis=0)
res = np.min(score, axis=0)  #这样我们就可以知道最小的81是第二排的，是从前往后遍历的
print(result, res)
# np.argmin告诉你最小值在哪里，np.min告诉你最小值是什么。通过组合使用，你可以精确定位到数据集中的极端值

# 9. 求每一列的标准差（这里是总体标准差）
# 标准差是一组数据平均值分散程度的一种度量。一个较大的标准差，代表大部分数值和其平均值之间差异较大；
# 一个较小的标准差，代表这些数据较接近平均值反应出数据的波动稳定情况，越大表示波动越大，越不稳定。
# 是数据分析中的核心指标，用于评估数据的稳定性、波动性和风险。例如，评估投资回报的波动性、产品质量的稳定性等
result = np.std(score, axis=0)
print(result)

# 10. 极 差
# 快速了解数据的总体范围，常用于数据预处理阶段，对数据的尺度有一个初步认识
result = np.ptp(score, axis=None)  #就是最大值和最小值的差
print(result)

[2 1] [75 81]
[2.94392029 3.29983165]
13


In [87]:
t = np.arange(30).reshape(10, 3)
np.mean(t, axis=0)

array([13.5, 14.5, 15.5])

# 数组的拼接

In [4]:
# 有的时候我们需要将两个数据加起来一起研究分析，我们就可以将其进行拼接然后分析
import numpy as np

# 1. 根据轴连接的数组序列，concatenate没有改变数组的维度
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([[9, 10], [11, 12]])
# # 要求a,b两个数组的维度相同
print('沿轴 0 连接两个数组：')
print(np.concatenate((a, b), axis=0))  #写哪个轴，哪个轴就变化
print('-' * 50)


沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
--------------------------------------------------


In [6]:
print('沿轴 1 连接两个数组：')
print(np.concatenate((a, b,c), axis=1))
print(np.concatenate((a, b,c), axis=1).shape)

沿轴 1 连接两个数组：
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]
(2, 6)


In [7]:
#堆叠
print('-' * 50)
print(np.stack((a, b,c), axis=1))  #stack会增加维度
print(np.stack((a, b,c), axis=1).shape)  #stack会增加维度

--------------------------------------------------
[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[ 3  4]
  [ 7  8]
  [11 12]]]
(2, 3, 2)


In [9]:
# 2. 根据轴进行堆叠，2维会变为3维
# for _ in range(10)表示我们只关心循环10次，不关心每次的计数值
# 在Python中，单下划线 _常作为临时变量名，用于表示一个不需要使用的值。
arrays = [np.arange(12).reshape(3, 4) for _ in range(10)]
print(arrays)
print(len(arrays))
print('沿轴 0 连接两个数组：')
result0 = np.stack(arrays, axis=0)
print(result0.shape)  #(10,3,4)
print (result0)



[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])]
10
沿轴 0 连接两个数组：
(10, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [

In [10]:
print('-' * 50)
print('沿轴 1 连接两个数组：')
print(arrays[0])
result1 = np.stack(arrays, axis=1)
print(result1.shape)  #(3,10,4)
print(result1)


--------------------------------------------------
沿轴 1 连接两个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 10, 4)
[[[ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]
  [ 8  9 10 11]]]


In [29]:
print('-' * 50)
print('沿轴 2连接两个数组：这里-1和2是等价的')
result2 = np.stack(arrays, axis=-1)
print(arrays[0])
print(result2.shape)
# print(result2)

--------------------------------------------------
沿轴 2连接两个数组：这里-1和2是等价的
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4, 10)


In [101]:


# # # 3. 矩阵垂直拼接，vstack没有增加维数，类似于concatenate   ---vertical
v1 = [[0, 1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10, 11]]
v2 = [[12, 13, 14, 15, 16, 17],
      [18, 19, 20, 21, 22, 23]]
result = np.vstack((v1, v2))
print(result)

# # # 4. 矩阵水平拼接，类似于concatenate  horizontal
v1 = [[0, 1, 2, 3, 4, 5],
      [6, 7, 8, 9, 10, 11]]
v2 = [[12, 13, 14, 15, 16, 17],
      [18, 19, 20, 21, 22, 23]]
result = np.hstack((v1, v2))
print(result)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 18 19 20 21 22 23]]


# 分割

In [102]:
# 1. 将一个数组分割为多个子数组
'''
参数说明：
ary：被分割的数组
indices_or_sections：是一个整数，就用该数平均切分，如果是一个数组，为沿轴切分的位置（左开右闭）
axis：沿着哪个维度进行切向，默认为0，横向切分。为1时，纵向切分
'''
import numpy as np

arr = np.arange(12).reshape(4, 3)
print(arr)
print('将数组分为三个大小相等的子数组：b是一个列表')
b = np.split(arr, 3, axis=1) #按那个轴，那个轴发生变化
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
将数组分为三个大小相等的子数组：b是一个列表
[array([[0],
       [3],
       [6],
       [9]]), array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]


In [103]:
b[0].shape

(4, 1)

In [104]:
b = np.split(arr, 4, axis=0)
print(b)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11]])]


In [105]:
c = np.hsplit(arr, 3)
print(c)  #c是列表
print(c[0].shape)

[array([[0],
       [3],
       [6],
       [9]]), array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]])]
(4, 1)


In [106]:
d = np.random.random((2, 6))
print(d)

[[0.8993456  0.75174723 0.54821909 0.7931341  0.32570986 0.48264758]
 [0.52652549 0.28356149 0.64989014 0.78267543 0.75831264 0.4543747 ]]


In [70]:
# # 2.numpy.hsplit 函数用于水平分割数组，通过指定要返回的相同形状的数组数量来拆分原数组。
harr = np.floor(10 * np.random.random((2, 6)))
print('原array：')
print(harr)


原array：
[[3. 6. 7. 5. 3. 1.]
 [1. 0. 6. 1. 8. 6.]]


In [108]:
# # 3.numpy.vsplit 沿着垂直轴分割
a = np.arange(16).reshape(4, 4)

print('第一个数组：')
print(a)
print('\n')

print('竖直分割：')
b = np.vsplit(a, 2)
print(b)

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


竖直分割：
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


# numpy inf和nan

In [109]:
'''
C 语言中表示最大的正整数值是 0x7FFF FFFF，最小的负整数是 0x8000 0000。
查阅资料后，发现 inf 表示无穷大，需要使用 float(‘inf’) 函数来转化，那么对应的就有	float('-inf') 表示无穷小了。
这样你就可以使用任意数来判断和它的关系了。
那什么时候会出现inf呢？ 比如一个数字除以0，Python中会报错，但是numpy中会是一个inf或者-inf
另外还有 nan，这种写法在 pandans 中常见，表示缺失的数据，所以一般用 nan 来表示。任何与其做运算结果都是 nan
'''
import numpy as np
#nan 是not a number的缩写，表示非数字，在numpy中表示一个非数字值，可以用来表示缺失数据
# 创建一个nan和inf #
a = np.nan
b = np.inf
print(a, type(a))
print(b, type(b))


nan <class 'float'>
inf <class 'float'>


In [110]:
# 并 且  np.nan != np.nan	结果 是TRUE
# 所以我们可以使用这两个结合使用判断nan的个数
print(np.nan == np.nan)
print(True == 1)
print(False == 0)
np.nan + 1  #nan和其他数运算的结果都是nan

False
True
True


nan

In [115]:
# --判断数组中为nan的个数
t = np.arange(24, dtype=float).reshape(4, 6)

# 将三行四列的数改成nan
t[3, 4] = np.nan
t[2, 4] = np.nan
print(t)


[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. nan 17.]
 [18. 19. 20. 21. nan 23.]]


In [116]:
# 可以使用np.count_nonzero() 来判断非零的个数
# print(np.count_nonzero(t))
print(t != t)
print('-' * 50)
print(np.count_nonzero(t != t))  # 统计nan的个数


[[False False False False False False]
 [False False False False False False]
 [False False False False  True False]
 [False False False False  True False]]
--------------------------------------------------
2


In [117]:
# 将nan替换为0
t[np.isnan(t)] = 0
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15.  0. 17.]
 [18. 19. 20. 21.  0. 23.]]


In [30]:
# ----------练习： 处理数组中nan
t = np.arange(24).reshape(4, 6).astype('float')
#
# 将数组中的一部分替换nan
t[1, 3:] = np.nan
print(t)
print('-------------------')
print(t.shape)
print(id(t))
# 遍历每一列，然后判断每一列是否有nan
for i in range(t.shape[1]):
    #获取当前列数据
    temp_col = t[:, i]

    # 判断当前列的数据中是否含有nan
    nan_num = np.count_nonzero(temp_col != temp_col)
    # 条件成立说明含有nan
    if nan_num != 0:
        # 将这一列不为nan的数据拿出来,并计算平均值
        temp_col_not_nan = temp_col[temp_col == temp_col]
        print(temp_col_not_nan)
        # 将nan替换成这一列的平均值
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)

print(t)
print(id(t))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
-------------------
(4, 6)
1823190023888
[ 3. 15. 21.]
[ 4. 16. 22.]
[ 5. 17. 23.]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
1823190023888


In [79]:
print(np.inf == np.inf)
np.inf

True


True

In [40]:
# np.nan和任何数据运算的结果都是nan
t = np.arange(24).reshape(4, 6).astype('float')
#
# 将数组中的一部分替换nan
t[1, 3:] = np.nan

t1 = np.arange(24).reshape(4, 6).astype('float')
t + t1

array([[ 0.,  2.,  4.,  6.,  8., 10.],
       [12., 14., 16., nan, nan, nan],
       [24., 26., 28., 30., 32., 34.],
       [36., 38., 40., 42., 44., 46.]])

In [82]:
arr = np.array([-1, 0])
print(arr)
print(arr[0] / arr[1])  #1除0就会得到inf

[-1  0]
-inf


C:\Users\Administrator\AppData\Local\Temp\ipykernel_10692\576235320.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  print(arr[0]/arr[1])  #1除0就会得到inf


In [83]:
np.nan + np.inf

nan

# 转置和轴滚动

In [84]:
#对换数组的维度
import numpy as np

a = np.arange(12).reshape(3, 4)
print('原数组：')
print(a)
print('\n')

print('对换数组：')
# 讲解transpose函数
print(np.transpose(a))
print(a)

# 与transpose一致
a = np.arange(12).reshape(3, 4)

print('原数组：')
print(a)
print('\n')

print('转置数组：')
print(a.T)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [12]:
# 在原基础上增加用例
import numpy as np

# 创建 3x4 的二维数组，元素为 0 到 11
a = np.arange(12).reshape(3, 4)
print('原数组：')
print(a)  # 形状 (3, 4)
print('\n')

print('对换数组（使用 transpose()）：')
# transpose() 默认反转所有轴（二维即交换行和列）
transposed_a = np.transpose(a)
print(transposed_a)  # 形状变为 (4, 3)
# 验证原数组未改变（转置返回新视图，但原数组引用未变）
print('原数组保持不变：')
print(a)  # 形状仍为 (3, 4)
print('\n')

# 重新初始化数组以演示 .T 属性
a = np.arange(12).reshape(3, 4)
print('原数组：')
print(a)
print('\n')

print('转置数组（使用 .T 属性）：')
# .T 与 transpose() 在二维数组等价
print(a.T)  # 输出与 transpose() 相同
print('\n')

# 扩展：多维数组转置示例（参考搜索结果[1,7](@ref)）
print("--- 多维数组转置演示 ---")
b = np.arange(24).reshape(2, 3, 4)  # 三维数组，形状 (2, 3, 4)
print("三维数组 b 的形状:", b.shape)
# 使用 transpose 自定义轴顺序（如将轴顺序改为 (1, 0, 2)）
# transopse() 第一个参数为轴序，第二个参数为轴的新顺序
b_transposed = b.transpose((1, 0, 2))
print("转置后形状 (轴序 1,0,2):", b_transposed.shape)  # 变为 (3, 2, 4)
# .T 默认反转所有轴（等价于 transpose(2,1,0)）
print("b.T 的形状（默认反转轴）:", b.T.shape)  # 变为 (4, 3, 2)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组（使用 transpose()）：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
原数组保持不变：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组（使用 .T 属性）：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


--- 多维数组转置演示 ---
三维数组 b 的形状: (2, 3, 4)
转置后形状 (轴序 1,0,2): (3, 2, 4)
b.T 的形状（默认反转轴）: (4, 3, 2)


In [85]:
# swapaxes函数用于交换数组的两个轴
t1 = np.arange(24).reshape(4, 6)
re1 = t1.swapaxes(1, 0)

print(' 原 数 组 ：')
print(t1)
print('\n')
print(re1.shape)
print('调用 swapaxes 函数后的数组：')
print(re1)


 原 数 组 ：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


(6, 4)
调用 swapaxes 函数后的数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [33]:
t3 = np.arange(60).reshape(3, 4, 5)
print(t3.shape)
print('-' * 50)
t3 = np.swapaxes(t3, 1, 2)
print(t3.shape)
# print(t3) 数据不用记住，不用观察

(3, 4, 5)
--------------------------------------------------
(3, 5, 4)


In [91]:
# 数组的轴滚动,swapaxes每次只能交换两个轴，没有rollaxis方便，默认情况下轴滚动最前面
a = np.ones((3, 4, 5, 6))
# np.rollaxis(a, 2).shape
np.rollaxis(a, 3, 1).shape

(3, 6, 4, 5)

In [14]:
#数据拷贝，copy()和赋值的区别
# 修改b不会影响a

b = np.array([[1, 2, 3], [1, 2, 3]])
a = b.copy()
print(id(a))
print(id(b))
a

1943103483184
1943058566864


array([[1, 2, 3],
       [1, 2, 3]])

In [15]:
b[0, 0] = 3
print(b)
a

[[3 2 3]
 [1 2 3]]


array([[1, 2, 3],
       [1, 2, 3]])

In [16]:
#随机数生成
arr = np.random.rand(2, 3, 4)
print(arr)

[[[0.87448526 0.06033293 0.19173567 0.55765683]
  [0.84709306 0.20534491 0.07365164 0.83739856]
  [0.36904901 0.98055842 0.9515624  0.22695558]]

 [[0.82154915 0.48839029 0.19086762 0.96087206]
  [0.74052323 0.58710162 0.9207953  0.48374559]
  [0.73135703 0.03598267 0.27729927 0.17477219]]]


In [ ]:
# 1. 均匀分布的随